-- Neon PostgreSQL schema. Set DATABASE_URL to a Neon connection string before applying.
CREATE TABLE IF NOT EXISTS aircraft (id TEXT PRIMARY KEY, registration TEXT UNIQUE NOT NULL, model TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS flights (id TEXT PRIMARY KEY, aircraft_id TEXT NOT NULL REFERENCES aircraft(id), phase TEXT, started_at TIMESTAMPTZ, ended_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS telemetry (id BIGSERIAL PRIMARY KEY, flight_id TEXT NOT NULL REFERENCES flights(id), aircraft_id TEXT NOT NULL REFERENCES aircraft(id), recorded_at TIMESTAMPTZ NOT NULL, altitude DOUBLE PRECISION NOT NULL, airspeed DOUBLE PRECISION NOT NULL, vertical_speed DOUBLE PRECISION NOT NULL, pitch DOUBLE PRECISION NOT NULL, roll DOUBLE PRECISION NOT NULL, heading DOUBLE PRECISION NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, flight_phase TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS anomalies (id BIGSERIAL PRIMARY KEY, flight_id TEXT NOT NULL REFERENCES flights(id), aircraft_id TEXT NOT NULL REFERENCES aircraft(id), recorded_at TIMESTAMPTZ NOT NULL, anomaly_score DOUBLE PRECISION NOT NULL CHECK (anomaly_score BETWEEN 0 AND 100), severity TEXT NOT NULL, detected_parameters JSONB NOT NULL, model_version TEXT NOT NULL, flight_phase TEXT NOT NULL, explanation TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS alerts (id BIGSERIAL PRIMARY KEY, anomaly_id BIGINT NOT NULL REFERENCES anomalies(id), status TEXT NOT NULL DEFAULT 'DETECTED', alert_type TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), acknowledged_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS model_versions (id BIGSERIAL PRIMARY KEY, version TEXT UNIQUE NOT NULL, model_type TEXT NOT NULL, features JSONB NOT NULL, metrics JSONB NOT NULL, training_samples INTEGER NOT NULL, validation_samples INTEGER NOT NULL, test_samples INTEGER NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_telemetry_flight_time ON telemetry(flight_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_anomalies_severity ON anomalies(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
